Repository metabrainz/picard-plugins, pull requests merged in 2023-07, with the labels that each got.

#355 replaygain2: fix several issues with with call to window.set_statusbar_message
  plugins/replaygain2/__init__.py
Labels: bug

#354 Add "Additional Artists Details" plugin
  plugins/additional_artists_details/__init__.py
  plugins/additional_artists_details/docs/README.md
  plugins/additional_artists_details/docs/option_settings.png
  plugins/additional_artists_details/options_additional_artists_details.ui
  plugins/additional_artists_details/ui_options_additional_artists_details.py
Labels: new plugin

#333 Add Genre Mapper plugin
  plugins/genre_mapper/__init__.py
  plugins/genre_mapper/options_genre_mapper.ui
  plugins/genre_mapper/ui_options_genre_mapper.py
Labels: new plugin

#357 Update Submit Folksonomy Tags plugin to match the revised format of call to MBAPIHelper class in Picard
  plugins/submit_folksonomy_tags/__init__.py
Labels: bug, enhancement

#356 Update Submit ISRC plugin to match the revised format of call to MBAPIHelper class in Picard
  plugins/submit_isrc/__init__.py
Labels: bug, enhancement
