Repository metabrainz/picard-plugins, pull requests merged in 2024-01, with the labels that each got.

#325 Fixes for "Generate M3U playlist" #245
  plugins/playlist/playlist.py
Labels: enhancement, need more work

#364 Add "as credited" sort variables to "Additional Artists Variables"
  plugins/additional_artists_variables/additional_artists_variables.py
Labels: enhancement

#371 Fix bug setting primary artist variables
  plugins/additional_artists_variables/additional_artists_variables.py
Labels: bug
